name: MLflow CI Pipeline (Advance)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas seaborn matplotlib

    - name: Run MLflow Project
      working-directory: ./MLProject
      run: |
        mlflow run . --env-manager local

    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-artifacts
        path: MLProject/mlruns

  build-docker:
    runs-on: ubuntu-latest
    needs: train-model

    services:
      docker:
        image: docker:dind
        privileged: true
        ports:
          - 2375:2375
        options: >-
          --dns 8.8.8.8

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Docker client
      run: |
        echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV

    - name: Install MLflow
      run: |
        python3 -m pip install --upgrade pip
        pip install mlflow

    - name: Download MLflow artifacts
      uses: actions/download-artifact@v4
      with:
        name: trained-artifacts
        path: mlruns

    - name: Find model path
      id: find_model
      run: |
        MODEL_PATH=$(find mlruns -type d -path "*/artifacts/model" | head -n 1)
        echo "model_path=$MODEL_PATH" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image from MLflow
      run: |
        mlflow models build-docker \
          -m "${{ steps.find_model.outputs.model_path }}" \
          -n ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci:latest
