name: MLflow CI Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    
    - name: Set MLflow Tracking Directory
      run: |
        echo "MLFLOW_TRACKING_URI=file://$GITHUB_WORKSPACE/MLProject/mlruns" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas seaborn matplotlib joblib

    - name: Run Training Script
      working-directory: ./MLProject
      run: |
        python modelling.py --data_path AI_Impact_on_Jobs_2030_clean.csv

  
    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        path: MLProject/mlruns


  build-docker:
    runs-on: ubuntu-latest
    needs: train-model

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MLflow
      run: |
        python -m pip install --upgrade pip
        pip install mlflow

    - name: Download MLflow Artifacts
      uses: actions/download-artifact@v4
      with:
        name: trained-model-artifacts
        path: mlruns

  
    - name: Find actual MLflow model folder
      id: find_model
      run: |
        MODEL_PATH=$(find mlruns -type d -path "*/artifacts/model" | sort | tail -n 1)
        echo "Model path found: $MODEL_PATH"
        echo "model_path=$MODEL_PATH" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image via MLflow
      run: |
        mlflow models build-docker \
          -m "${{ steps.find_model.outputs.model_path }}" \
          -n pradiptarafa/workflow-ci:latest

    - name: Push Docker image
      run: |
        docker push pradiptarafa/workflow-ci:latest
